### ISSUE TITLE
Error underline wrong when lines are indented using tabs

### ISSUE THREAD

**Issue by EmmaTheMartian** [Seggan/metis#1]
If you get an error on a line with tab indents then the error underline is off. I done some testing and I am pretty sure that it is because Metis' error system prints the tabs directly to the terminal however assumes that the tab width is only one character. This means that the underline is in the wrong location if the terminal renders tabs as more than one character.

As for a solution, you could replace tabs with four spaces when printing the messages and then add four spaces instead of adding one to the prepending spaces before the underline for tabs.

This image shows an erroneous line with no indentation:
![image](https://github.com/user-attachments/assets/c4405a12-d690-4099-ae61-b72194c6b613)

This image shows an erroneous line with a single tab indent:
![image](https://github.com/user-attachments/assets/3b312cce-6291-4294-b26d-b1ea30cb3540)

Here is the output of the error message from the second screenshot (single tab indent) piped to a file and highlighting the whitespace.
![image](https://github.com/user-attachments/assets/497e11c2-ed50-4f7c-b243-52e07222c3b3)

**Comment by Seggan** [comment]
Quick and dirty fix by replacing a tab with a space
